### ISSUE TITLE
Issue with hostname and hostname_key

### ISSUE THREAD

**Issue by svrsreeraj** [zarqman/fluent-plugin-syslog-tls#13]
Hello,

The following configuration is not updating the hostname in the syslog message.  If you comment the hostname it works, otherwise not. How can we set static/dynamic hostname for messages

   ```
@type syslog_tls
    host 10.10.10.10
    port 601
    client_cert /opt/path/td-agent/new_certs/client.pem
    client_key /opt/path/td-agent/new_certs/client.key
    ca_cert /opt/path/td-agent/new_certs/CA.pem
    verify_cert_name true
    facility user 
    severity_key severity 
    hostname static-hostname
    <format>
      @type json
    </format>
```

**Comment by zarqman** [comment]
Both `hostname` (for static) and `hostname_key` (for dynamic) should function just fine. For dynamic, the configured hostname key must already exist in the message payload--either from the original source, or added by a filter.

When you say it does not work when `hostname` is present, in what way does it not work? Do you get an error? Or does the syslog target host refuse or drop the messages?

Also, what versions of syslog_tls and fluentd/td-agent are you running?

---
Edited to add a couple more thoughts:
Using `verify_cert_name true` will require that your syslog server presents a cert with the name `10.10.10.10` (or whatever the real address/name is). If you only need to verify the cert's signature against your CA, that line can be dropped.
If your syslog server can be configured to disable client TLS verification temporarily, try doing so along with dropping all cert options in your <match> config. Just to confirm that basic TLS without the extra cert verification is working.
It it sometimes helpful to debug fluentd/td-agent with the `-vv` flag.

**Comment by svrsreeraj** [comment]
Sorry to inform you that it was a mistake that I was looking in different location
my rsyslog erver has aa template that will create directories based on the hostname
`$template DynamicFile,"/var/log/%HOSTNAME%/forwarded-logs.log"	
`
hostname , both static and dynamic are working just fine.
