### ISSUE TITLE
Multiple tcp sessions opened towards the rsyslog and they keep increasing

### ISSUE THREAD

**Issue by brucelee138** [zarqman/fluent-plugin-syslog-tls#14]
We are using the fluent-plugin-syslog-tls output plugin to stream container logs in Kubernetes cluster from fluentd to rsyslog with the following output config
```
<match {**namespace1**,**namespace2**,**namespace3**}>
  @type copy

<store>
  @type syslog_tls
  host abcd
  port 514
  ca_cert /fluentd-out/ssl/ca.crt
  client_cert /fluentd-out/ssl/tls.crt
  client_key /fluentd-out/ssl/tls.key
  verify_cert_name true
  hostname fluentd-logging
  facility SYSLOG
  format json
</store>
```

We are observing that 50+ tcp sessions are opened towards the rsyslog.
```
worker:~> lsof -i -P -n | grep 514
ruby.ruby 136252 messagebus   19u  IPv4 10438592      0t0  TCP 192.168.113.217:52166->10.221.58.167:514 (ESTABLISHED)
ruby.ruby 136252 messagebus   22u  IPv4 10437454      0t0  TCP 192.168.113.217:52162->10.221.58.167:514 (ESTABLISHED)
ruby.ruby 136252 messagebus   23u  IPv4 10437455      0t0  TCP 192.168.113.217:52164->10.221.58.167:514 (ESTABLISHED)
......
```
This no. keeps growing gradually and crosses the maxtcpsessions configured in rsyslog. Is there any config to control the no. of tcp sessions opened towards rsyslog server? How are these no. of sesssions to be opened determined?

Thanks in advance!

**Comment by zarqman** [comment]
A new connection is opened for each tag. Does your `<match ...>` have a huge number of dynamic (and growing) matches? If so, that might be the source of the connections.

If a tag disappears, the plugin relies on fluent to trigger clean up. I don't know if fluent actually has a facility to do that, however.

This part of the code was inherited from a fork years ago and is non-optimal in the modern kubernetes era where it's rather easy to end up with a ton of tags. Ideally it'd be refactored, but perhaps a workaround is possible too.

Thinking on a workaround, the idea would be to match all tags/namespaces as you are now, and rewrite the tag to a single, static value. Then, match on that new value for sending to syslog.

The tag is also used as the syslog `app_name` by default. If you don't mind losing that, then you're done. If you want to preserve that, then during the rewrite, store the original tag in another key. Inside the syslog store, add `app_name_key ORIGINAL_TAG_KEY_NAME`.

If you try the workaround, or settle on another solution, please share how that goes as it could help others too.

If the set of matching tags isn't varying, then something else could be going on. In that case, what version of fluent (and any other plugins) are you using?

**Comment by brucelee138** [comment]
@zarqman Thanks a lot for the explanation and work around.
We used the "rewrite_tag_filter" plugin to write tags of all containers to a static tag (we did per namespace).
This has brought down the TCP sessions count very much and I dont see the sessions growing anymore.
Thanks a lot for the help!

```
<match {**_namespace1_**}>
  hostname_command cat /etc/hostname
  @type rewrite_tag_filter
  <rule>
    key log
    pattern ^.+$
    tag kube.var.log.containers.namespace1
  </rule>
</match>
<match {kube.var.log.containers.namespace1}>
  @type copy

<store>
  @type syslog_tls
  host 10.221.58.167
  port 514
  ca_cert /fluentd-out/ssl/ca.crt
  client_cert /fluentd-out/ssl/tls.crt
  client_key /fluentd-out/ssl/tls.key
  verify_cert_name true
  hostname fluentd-logging
  facility SYSLOG
  format json
</store>
```

**Comment by zarqman** [comment]
@brucelee138 Glad to hear the workaround was successful. And, thanks for sharing your config!
