### ISSUE TITLE
TLS 1.3 support for fluent-plugin-syslog-tls

### ISSUE THREAD

**Issue by brucelee138** [zarqman/fluent-plugin-syslog-tls#15]
We are using the fluent-plugin-syslog-tls output plugin to stream container logs in Kubernetes cluster from fluentd to rsyslog and we are moving towards tls1.3 in our logging infra.

Does the "fluent-plugin-syslog-tls" support TLSv1.3? We could not find any option in the README regarding setting the tls version?
Also, could not find in https://github.com/zarqman/fluent-plugin-syslog-tls/blob/e3a6950d73d69bec36a2c82707620300d95f8f37/lib/syslog_tls/ssl_transport.rb as well. Is TLS1.3 supported currently?

Thanks in advance!

**Comment by zarqman** [comment]
@brucelee138, great question!

It looks like the `ssl_version` being set in `ssl_transport.rb` is a fixed version, while it would be better as a minimum version. Let me look into that.

**Comment by zarqman** [comment]
@brucelee138, I've released version `2.1.0.rc1` that supports TLSv1.3.

Before, it was fixed at TLSv1.2. Now only the minimum is TLSv1.2, but it will use newer versions too.

Please test and let me know how it goes. And thanks for raising the issue!

**Comment by brucelee138** [comment]
@zarqman that was quick! Sure, I would be testing this and would let you know the results.
Thanks!

**Comment by brucelee138** [comment]
@zarqman Sorry for the delayed response. Had hit a snag while trying to force tls1.3 from the log receiver we used.
Tls1.3 is working now with the 2.1.0.rc1. Thanks a lot for your support!
![tlsJPG](https://user-images.githubusercontent.com/19279243/216291879-6bd60ef0-db0c-4001-951a-2e562fe90a98.JPG)
![tls1](https://user-images.githubusercontent.com/19279243/216291924-564b4637-6375-4583-9acc-0b43788d855d.JPG)

**Comment by brucelee138** [comment]
@zarqman 1 follow up query, there is no means to force the minimum tls version currently from the fluent-plugin-syslog-tls though right?

**Comment by zarqman** [comment]
@brucelee138 Thanks much for following up, and glad to hear everything is working as expected.

Correct, the plugin's minimum version is currently hardcoded at TLSv1.2.
