### ISSUE TITLE
Support UDP

### ISSUE THREAD

**Issue by scalp42** [zarqman/fluent-plugin-syslog-tls#6]
Hi @zarqman 

Came across your gem after running into issues with the `remote_syslog` one (see https://github.com/dlackty/fluent-plugin-remote_syslog/issues/35 for background).

Do you have any plans for supporting UDP?

Let me know and thank you for your plugin!

**Comment by zarqman** [comment]
@scalp42 This plugin is intended to be TLS-only, which as far as I know requires TCP. As such, no, there are no plans for UDP support.

**Comment by scalp42** [comment]
Would you be open to a PR that allows UDP?

**Comment by zarqman** [comment]
I'd like to keep the plugin as TLS-only (it's even in the name!). Since I don't believe TLS over UDP is possible, adding UDP seems out of scope. (But if you know something I don't about TLS + UDP, then by all means let me know.)

Is there not a syslog/udp plugin or two already available?

**Comment by scalp42** [comment]
Sorry I was meaning without TLS support obviously.

I got the message loud and clear, we'll look into different directions.

Thanks again.
